// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_bhErBI91XXL6z-Gv7hnqDRefaNfJLk',
    appId: '1:941164656793:web:7ea796d632fa9ee87d6008',
    messagingSenderId: '941164656793',
    projectId: 'pantrysnap-e9dd6',
    authDomain: 'pantrysnap-e9dd6.firebaseapp.com',
    storageBucket: 'pantrysnap-e9dd6.firebasestorage.app',
    measurementId: 'G-7ZC6L9WRP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuL4vGisKUSlVTAUDmWlih_Vd_6JcwT4',
    appId: '1:941164656793:android:cb93f04afbd0efa17d6008',
    messagingSenderId: '941164656793',
    projectId: 'pantrysnap-e9dd6',
    storageBucket: 'pantrysnap-e9dd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21hCi4_pl_BWm7FRWFXYvsEhpKztlB5Y',
    appId: '1:941164656793:ios:31732328fe26bca87d6008',
    messagingSenderId: '941164656793',
    projectId: 'pantrysnap-e9dd6',
    storageBucket: 'pantrysnap-e9dd6.firebasestorage.app',
    iosClientId: '941164656793-nemnj1e4t9ejpr953docrm5tbgmpsp85.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantrysnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD21hCi4_pl_BWm7FRWFXYvsEhpKztlB5Y',
    appId: '1:941164656793:ios:31732328fe26bca87d6008',
    messagingSenderId: '941164656793',
    projectId: 'pantrysnap-e9dd6',
    storageBucket: 'pantrysnap-e9dd6.firebasestorage.app',
    iosClientId: '941164656793-nemnj1e4t9ejpr953docrm5tbgmpsp85.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantrysnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA_bhErBI91XXL6z-Gv7hnqDRefaNfJLk',
    appId: '1:941164656793:web:9fb023ddf0c65e197d6008',
    messagingSenderId: '941164656793',
    projectId: 'pantrysnap-e9dd6',
    authDomain: 'pantrysnap-e9dd6.firebaseapp.com',
    storageBucket: 'pantrysnap-e9dd6.firebasestorage.app',
    measurementId: 'G-6HLP8M1RSB',
  );
}
